### ISSUE TITLE
`Action shell not handled`

### ISSUE THREAD

**Issue by erikw** [wonderbeyond/dotbot-if#1]
Hey,

using the latest version of this plugin and a doubt installation configuration containing only the partially modified example from this README:

```yaml
- if:
    cond: 'true'
    met:
    - shell:
      - echo Found Python 3.
```

then running `./install` gives me

```console
$ ./install -v
Action shell not handled

==> Some tasks were not executed successfully
```

What could be wrong here? I tried other actions than `shell` but I get the same output.
