### ISSUE TITLE
initializing dotbot-if has dotbot do duplicate work for calls to default plugins

### ISSUE THREAD

**Issue by smergler** [wonderbeyond/dotbot-if#3]
`if.py` imports the following default `dotbot` plugins for use if they are needed later on in the process.  
- Clean 
- Create
- Link
- Shell

When `dotbot` goes through its list of plugins loaded, it seems to call those plugins twice. 

For example, given the simple `install.conf.yaml` file 
```
- if:
    cond: 'python -V | grep -Eq "Python\s+3\."'
    met:
    - shell:
      - echo Found Python 3.
    unmet:
    - shell:
      - echo Python3 not found!
```

In a directory that only contains that file, the `dotbot-if` and `dotbot` repos, this is the output of `install` 

<img width="360" alt="Screenshot 2024-07-14 at 12 04 43 AM" src="https://github.com/user-attachments/assets/8bd256b8-0a3d-46ad-b824-5e3c7f8377f3">

The assumed output is the following: 

<img width="418" alt="Screenshot 2024-07-14 at 12 04 59 AM" src="https://github.com/user-attachments/assets/3b180891-4c22-49d0-8340-7317f45616b4">

As we can see, the command was run twice.  In further tests with more complicated configs, `dotbot` seems to run every default plugin twice but only externally created plugins once while using `dotbot-if`

This seems to be due to a bug in the logic that `dotbot` uses to load modules.  However, `dotbot-if` is an extremely rare case that it is one of the few external plugins that use those default plugins.  A band-aid fix here should be easier than possibly breaking `dotbot`'s logic.
